language: ruby
rvm:
- 2.4.1
sudo: false
before_install:
- npm install -g bower
- bower install
- travis_retry bundle install
script: jekyll build
after_success:
- chmod +x scripts/deploy.sh
- scripts/deploy.sh
branches:
  only:
  - master
env:
  global:
  - DEPLOY_BRANCH=master
  - secure: y9uCV0D0MqxcDRLxsmWtI8sfbmZVI2VGUjNK1v6mv5/Ep1e+wfDCT4UXZICm2KO0PtAzNwrR86H0e66CPT+Pivj8v0L914ub1KlDSL62ptxBKe/ZmJkwtWXc1Lv1FgXhT/tsEmd1k2gGV5S0rFRRVDMzzK1Dlogn+aVYiwiyIRNDsJ2vmvOAw15wZ0HiT1qM6eOZHEAZMli6kL8DLc4DbexdExsnvUi+vuuCegZBGuXfMDWkE7iK/24A3QpT4Xvi1UYNxSOz6F2QvLFtfWmhar2M2KNe5r7p6fPg1e0Ao/QC3MgTfyoO/0C5lW2Efar9rWuTFsIVsmrSkw8zSUHpaR+9JP+TiWZVM4bfnAATyuZmtsbxvoB9RKNH4GbZ+7fpg/9dpQCuh1dqrTiCO42s4Ks6HNOqafRfAGBbSiDFh504M8w/bwoFTjD3LAHhwaWzyX/Eqs0Ay0759MTO1i0QQc6ynxPM9/aw76uorn9TYW4BDHlUzhQXgCIgQ3FEmjpevsBUDVV8oxl47OBQk8qKru26y4hT4JCzYAilJSLsWOPZMABsMK0xih/wWu/rLl715k1xzxfhTTCuOcULgy3miFJPuDAcWehSxG+WEtB/zZMX+hMFj0gXKaI4ToBINl241d9hXQ8ZPdEfjRHDov/eR3azZsKgfEyKWkIIyi3TIHU=
  - secure: C617If5qe6aEMGd9BNbmBiEynWZutFlFjACI7WaS8JMPpsqlaxK99RH8klh9BdqREheRb2XmM3c0Ot+Ahth7vU3HF3xYRJbxW37Xy7geeRSkfD9EEFjj5cLuSJI3lpl7xyo/EizK8Z6KOU1f8Q64uaiAUbYe3YlmbQFmJYtQy5TgR457QiZJB9KjKXT6J7OVOyt8q0B0RsLXnG+h+seVFYUmPVYu+an+YS3PTLt1yJgaujrSbU3ac/ELqjejtOzc13zH6yDkNdKxo07mq1dHXNb71X54IIURvUmYM6Wh2Lo3HzhUNOnfMBK9oTt1Qixf8rFDgnxqttGiRfHnPFEL2PDAOPUQYTczbaDCev1JvKOU6x2WCvepAMvYm62pVSaL1RnWOwxP6z+zE8RVLJW5jFWs8kXLqqUwRrICdHZVmlXZDChOeGmFelumhD/BQ1C/ugNwDqZTjcAhgXkGWzJhkZHfsKdK/Kd9TXRTw6LlxgrvIw876adhrWgzNd/gdVcSFU+c470pGdWU+uoADEI2cZm9tW/es561Br7iUUyX10jy4f7WmksOL+7rU3yNEo91UkmB6uvPhb13sUxngp69cP0w9sUJT0JfenZvvvH40hWmZEVT2JhxWXO/bsL3WOACj9Q9hE7thO0WGdqEpkLaNBXBJ0EUxcXbB8el86Q9IKI=
