language: ruby
rvm:
- 2.4.1
sudo: false
before_install:
- npm install -g bower
- bower install
- travis_retry bundle install
script: jekyll build
after_success:
- chmod +x scripts/deploy.sh
- scripts/deploy.sh
branches:
  only:
  - master
env:
  global:
  - DEPLOY_BRANCH=master
  - secure: iIC8wh7ZuCswKmd9xUWHIwV/B8Pky9jnrfF95SKfy/G57fB71Jv8UUObfuNZQmjRl6X6h5XT67PeFBmWHO88itDUrAYgcFOx/MRrn7sjY1Uvvb9epdK8QtGzqwFpCZ0+hZmPjsju66ajKXSQM4T01qxmmfVtU9ZEBMCPPsI9absGMF0Yzx1/pAWMki7+wcCK5z8Qrw+jWn2H8oyIZ3Tft2l2Eaz/iKp8ncRnTao+VcLRSSRYNseE+aoL/3S6dudawtb/A+H3H67XkgYk2wGDJuWBn64L2WdsX8iw6048kdX6iuK50VDMaP8veNOWCKWSK5tY6WyqChydlT3576+/u9WfHWuNgWZ/CO0k0eHUoZsht1zgkCNLeQZLvsbX86atrs1P02bcinNvnkBeCku1fKuaByvnUILP9d4kcmoIeDXI2XYiu4u5N0vWSHbNljw0cevkh217wIgnraNUMr9geaKtdpG/393KGPgrxd0XoWrdOFST2MSi6Cuo+4Za9jaMX5gjPxJeezS/Nyfg/iGxJbFhzOYMNTIj3a03KS6+Py+gdYlLhDLcqr7eBPhH+9z+iZlF2sfS8pwjxpq/fuhVyHnpbaTmc6RNZR03355VBoZ8ca7KG62HIjkA9QrxG9OJsrmgyApn2GBW3EXm15kUXvNy7tnc6Z09KKzAxtyJf8c=
  - secure: gRKjrJjLEQy84PR85LwWQ+ybfir/gbA0l/OprCJcql17N3jJ2jpJCWHO/aO4vACAU2i4jd7fQvAwcY3BTHtsugLmRDM+YfsYewJjUq4WGGbT8cJT0+9fdSVAAArlUb93fouG54iGSK4Rqek25F2cUupUNwTe4gGxTIKct7K8FYFNbN0aKtPT2FJavkNBfEkt9SHL1lktEy2Kj1sOpOvuaXLt2iMkW9eBk4MJdqR1dn76nbwRPKoWJ8XFl8+33RxEdMbCcLff80mokgrF2WNueCPOINIki1JSB1MzAPY/UemcyGFVlBQKVtQOZvwWQ1dwjaKmlFIJ80vho5rBE03ljLbWgPDGzYxcMJhbLIcJ8GDkQJG/AxUJgYG9osUOlc/k/lvd3SN0i+D4+2m48Zd83DZK78t/Oi3VZaQ3hRVYz/QbR3bFEozFuqX+ubCvCaVehX6/sUHlzhetqxqXy7PU9XXcWWub3o1OkMBJT4t5IbEcqBP9WDthL4Rfdbmam5b3i4q0hGYcy7rJxegc5Rw30ORBf0a4UjkrIcS7Qyc+uxo6z9c2ZkVtqtrQWspn3LeI8y0Im4D9WGAA+XWL9NJDIsgrVADEshinqklUTzFLBb/x/igGrFm3v790pHvqKF/5TkKjIruV7WKxOTRgulmAkennQ3gcns9RuNRQavLh33M=
