language: ruby
rvm:
- 2.4.1
sudo: false
before_install:
- npm install -g bower
- bower install
- travis_retry bundle install
script: jekyll build
after_success:
  - chmod +x scripts/deploy.sh
  - scripts/deploy.sh
branches:
  only:
  - master
env:
  global:
  - secure: CrSHzNMBnQfgqbC2/w55i3tsdrUavJw0zaenuBbZLW3STf1N9CaL+CKeGMRlZnlmUIHdwRuYHgv3P5CF8KaGnikXiHSMjScnupF2wEbTt882S1CdS8g2dR7G8YxCl9tHaN2TVSdrHawQtVwFM8RCTzknvdPhvt7zG9gynMAExvIcLkPsUjL9iiuLFpv2IjfQqtN+LFheijU6hCVh+CylXv331e2e7ce14Oi0AK4+F58mgq69bax0ERd8n3PiXsz8XfQY3IMOZdkk2mGlDx7dURez1MP+U4dx31rEWtPBY1t5kGxA1tqpre3u5JNYSUtlC1KDRamwdIQ2V1aumR6b0cu8NVjcmzPaChkUx+2eesaH7JY2/z1YEYdMfjUzz8sED45bCxPRjPPdipwp80r4vb1AHXaaOlVyWQNkMFvVFGcIfs7Wrzs5gzIJjg+JI9E8drHbyTHSFyasW8fvdZiPo6KQyyRmsBZvYXlx/TR9qy6696f7l/0E0j8G5PLnIJ1sCDZC03/qHey85Ja3e4CFczHOBnf7S48RB6PXNlwIUf2XAemWZq+aohYiKp04sFioSfrzAa1SSoSlNEmaM9V2KYtk0mbNG+IuaKhWq4pFbVHVwIcmnw4orTrEkIwMaAy+McP7W9eP5JrR0FeacexSE7pjNs6IbSi2v0E9IXASo/s=
  - secure: Aa1W4p0sF7ez9qe6zU6T1KSL3KMNLtvG9xmfX8yOJCFhmVWV1wKKKiRHs4YVJjf1Yz4Tc+xdZMFsu9Y8HaNvgs9JggYxToz50yhVqPcxZXVwrtVCbWikBuJhxpSBy4BR9fB4OioyByUmm2Z8OGffNcx2KZw4zyZm+bsKflTptYF9h+NIzsOOsLD6tYg9U+Q7kdcalwOeMJZC1YFFZf99lOvKFlaFEvQeWkJIAs25UmuKe0hOsz4oxW4Mc0AzeM+Js6UeFrVWDYBSjs6ROJmK9XNEGt8hIrBbwDgOCwxObGwYtlY63CaF3gf98L2nuNMCq9iFqK9HfOzIQ1qq7UvpAwX0dp+nCoa8WbbcbgVxGkT5oXDyGBaNKOHsI7Ssp0cwymD5ZpZ+fZr7pNPncrz6ayAGgHYM9vhnDYBo7CED6nr6BFvzFFpwFE1wjRi7QOmPnX6SOOsVBDClGnPFWes4WP4g6vP/3/ZkYiy9183PLEJgAmnw+O3H6FcZ4+GH5+lhJSpyfNeOYaXhIf0mYkWdakRcin7IAWVLzTDXDTE1qNBh5dULwxeGhNO5vd6pf2MAP/1vz40R85Gv8OMsZl10rx2kgmsaThwI1GO9cgYuQB8FwNuCPfAYW0N2rTNhzQYKNQyELyOHyp2jiRoIxvNVKFoJgcAl/ZM1tfpgsX/Gz+o=
